"""
Generate GitHub-ready reconstruction project + ZIP.
Rewrites resource references to local paths.
"""

from __future__ import annotations

import json
import re
import shutil
import zipfile
from pathlib import Path
from typing import Any, Dict, List, Optional


def rewrite_references(content: str, url_to_local: Dict[str, str], content_type: str = "html") -> str:
    """Replace remote URLs with local relative paths where we have them."""
    if not content or not url_to_local:
        return content

    # Longest URLs first to avoid partial replacements
    for remote, local in sorted(url_to_local.items(), key=lambda x: -len(x[0])):
        # Make local path relative-friendly
        local_ref = "/" + local.lstrip("/") if not local.startswith(("http", "/")) else local
        # Also try without leading slash for relative
        content = content.replace(remote, local_ref)
        # protocol-relative
        if remote.startswith("https://"):
            content = content.replace(remote.replace("https:", ""), local_ref)
        elif remote.startswith("http://"):
            content = content.replace(remote.replace("http:", ""), local_ref)
    return content


def write_readme(dest: Path, report: Dict[str, Any], original_url: str) -> None:
    purpose = report.get("purpose") or {}
    techs = report.get("technologies") or []
    tech_list = ", ".join(t.get("name", "") for t in techs) or "Unknown"

    readme = f"""# Reconstructed Site

> Auto-generated by **Website Reverse Engineering** platform  
> Source URL: `{original_url}`

## Purpose / Positioning

- **Title**: {purpose.get("title") or "N/A"}
- **Description**: {purpose.get("description") or "N/A"}
- **Inferred positioning**: {purpose.get("inferred_positioning") or "N/A"}
- **Explicit motto/slogan**: {purpose.get("explicit_motto_or_slogan") or "(none found)"}

## Detected Technologies

{tech_list}

## Project Structure

```
reconstructed-site/
├── README.md
├── package.json
├── .env.example
├── public/
│   ├── images/
│   ├── icons/
│   └── fonts/
├── src/
│   ├── pages/
│   ├── components/
│   ├── styles/
│   ├── scripts/
│   └── data/
├── backend/          # only if authorized material was available
├── assets/
├── reports/
├── manifests/
└── deployment/
```

## Setup

```bash
# Install dependencies (if package.json present)
npm install

# Copy environment template
cp .env.example .env
# Edit .env with required values (no secrets were collected)

# Serve static pages (simple)
npx serve public
# or open src/pages/*.html directly in a browser
```

## Deployment Notes

- This reconstruction contains **only publicly accessible** frontend material collected during analysis.
- Backend / server-side code is **not** included unless the project owner supplied authorized files.
- Some assets or API endpoints may be missing (see `manifests/resources.json` and `deployment/deployment.md`).
- Dynamic server-rendered content may appear as static snapshots of the rendered DOM.

## Manifests

- `manifests/resources.json` — every collected artifact (URL → local path → status)
- `manifests/routes.json` — discovered pages / routes
- `manifests/technologies.json` — technology fingerprints with evidence

## Reconstruction Status

See `reports/` for the full technical report and `deployment/deployment.md` for the checklist of missing resources.
"""
    (dest / "README.md").write_text(readme, encoding="utf-8")


def write_package_json(dest: Path, title: str) -> None:
    pkg = {
        "name": "reconstructed-site",
        "version": "1.0.0",
        "private": True,
        "description": f"Reconstructed from {title}",
        "scripts": {
            "start": "npx serve public -p 3000",
            "serve": "npx serve . -p 3000",
        },
        "dependencies": {},
    }
    (dest / "package.json").write_text(json.dumps(pkg, indent=2), encoding="utf-8")


def write_env_example(dest: Path) -> None:
    (dest / ".env.example").write_text(
        "# Environment variable names only — no secrets were collected\n"
        "# Add values required by the original application if known\n"
        "NODE_ENV=production\n"
        "PORT=3000\n",
        encoding="utf-8",
    )


def write_deployment_md(dest: Path, missing: List[str], report: Dict) -> None:
    lines = [
        "# Deployment Checklist",
        "",
        "## Available",
        f"- Pages collected: {report.get('pages_crawled', 0)}",
        f"- Assets collected: {len(report.get('asset_manifest', []))}",
        f"- Technologies detected: {len(report.get('technologies', []))}",
        "",
        "## Missing / Unavailable Resources",
    ]
    if missing:
        for m in missing:
            lines.append(f"- [ ] {m}")
    else:
        lines.append("- (none recorded)")
    lines.extend(
        [
            "",
            "## Notes",
            "- Backend services and private APIs cannot be reconstructed from public frontend alone.",
            "- Authentication, databases, and server-side logic require authorized source material.",
            "- After `npm install` (if applicable), serve the static files and verify page structure.",
        ]
    )
    (dest / "deployment" / "deployment.md").write_text("\n".join(lines), encoding="utf-8")


def build_reconstruction(
    job_dir: Path,
    report: Dict[str, Any],
    pages: Dict[str, Any],
    url_to_local: Dict[str, str],
    asset_manifest: List[Dict],
    original_url: str,
) -> Path:
    """
    Create reconstructed-site/ directory tree and ZIP it.
    Returns path to the ZIP file.
    """
    recon_root = job_dir / "reconstructed-site"
    if recon_root.exists():
        shutil.rmtree(recon_root)

    # Directories
    for sub in (
        "public/images",
        "public/icons",
        "public/fonts",
        "src/pages",
        "src/components",
        "src/styles",
        "src/scripts",
        "src/data",
        "backend/routes",
        "backend/services",
        "backend/config",
        "assets",
        "reports",
        "manifests",
        "deployment",
    ):
        (recon_root / sub).mkdir(parents=True, exist_ok=True)

    # Copy already-downloaded assets into the reconstruction tree
    downloads_root = job_dir / "downloads"
    if downloads_root.exists():
        for item in downloads_root.rglob("*"):
            if item.is_file():
                rel = item.relative_to(downloads_root)
                target = recon_root / rel
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(item, target)

    # Write HTML pages with rewritten refs
    routes = []
    for url, pdata in (pages or {}).items():
        html = pdata.get("html") or pdata.get("rendered_html") or ""
        if not html:
            continue
        rewritten = rewrite_references(html, url_to_local, "html")
        # filename from path
        from urllib.parse import urlparse
        path = urlparse(url).path.strip("/") or "index"
        safe = re.sub(r"[^\w.\-/]", "_", path).replace("/", "_") or "index"
        if not safe.endswith(".html"):
            safe += ".html"
        page_path = recon_root / "src" / "pages" / safe
        page_path.write_text(rewritten, encoding="utf-8")
        routes.append({"url": url, "local": f"src/pages/{safe}"})

    # Manifests
    (recon_root / "manifests" / "resources.json").write_text(
        json.dumps(asset_manifest, indent=2), encoding="utf-8"
    )
    (recon_root / "manifests" / "routes.json").write_text(
        json.dumps(routes, indent=2), encoding="utf-8"
    )
    (recon_root / "manifests" / "technologies.json").write_text(
        json.dumps(report.get("technologies") or [], indent=2), encoding="utf-8"
    )

    # Report copy
    (recon_root / "reports" / "summary.json").write_text(
        json.dumps(
            {
                "url": original_url,
                "purpose": report.get("purpose"),
                "technologies": report.get("technologies"),
                "architecture": report.get("architecture"),
                "pages_crawled": report.get("pages_crawled"),
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    write_readme(recon_root, report, original_url)
    write_package_json(recon_root, (report.get("purpose") or {}).get("title") or original_url)
    write_env_example(recon_root)

    missing = [
        a["original_url"]
        for a in asset_manifest
        if a.get("status") != "collected"
    ]
    write_deployment_md(recon_root, missing, report)

    # ZIP
    zip_path = job_dir / "reconstructed-site.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in recon_root.rglob("*"):
            if f.is_file():
                zf.write(f, f.relative_to(recon_root.parent))
    return zip_path
